### ISSUE TITLE
ply viewer

### ISSUE THREAD

**Issue by SunshineDou** [reefactor/ply_viewer#1]
Hello,
I have a 3D model of a room in ply format, and I want to use OpenGL to display it in the first step, and then use opengl virtual camera to realize roaming in the room. I want to know can I use this project to realize it? if it can, How can I run it? could you please give a more detailed discription as I am not familiar with qt?
Thanks very much

**Comment by reefactor** [comment]
feel free to use it, its MIT licence https://github.com/reefactor/ply_viewer?tab=MIT-1-ov-file#readme

Build it with Qt Creator, just open  pcviewer.pro
